language: scala

jdk:
  - oraclejdk8

script:
  ## runs both regular tests and sbt-scripted integration tests
  - sbt -Dfile.encoding=UTF8 test scripted bintrayDumpCredentials

after_success:
  - '[[ $TRAVIS_BRANCH == "master" ]] || [[ $TRAVIS_BRANCH =~ ^v[0-9.]+$ ]] && sbt "such publish"'

sudo: false

# https://docs.travis-ci.com/user/languages/java/
addons:
  apt:
    packages:
      - oracle-java8-installer

before_cache:
  # Tricks to avoid unnecessary cache updates
  - find $HOME/.sbt -name "*.lock" | xargs rm
  - find $HOME/.ivy2 -name "ivydata-*.properties" | xargs rm

# These directories are cached to S3 at the end of the build
cache:
  directories:
    - $HOME/.ivy2/cache
    - $HOME/.sbt/boot/

env:
  global:
    - BINTRAY_USER=jastice
    - secure: "jMKMsF3/Bzw8YkidcdsXoaygUVfgbOMnU7tnk3q7Hly5zhIzZe3iBNYvhk1WB1hR3ntT1kCYsnQN3nh4Y/HjuNrSloKZEQeKeAXQbcxlNoqpkkCMRgJChzU8H4LEGIThBoWv8plR0n/yy7bZCjCxZcxjusaOQ8iM5BB015CsIk5Y8A0xJIR2bqhAy7MmCejZ62fgCywZZcgG26L+HCDDeKB7ldSu77ou3BD4HBHqhTk07y2mBIa7ZWncZ4DU8jwFX7wZOUF6TWbP5UZNJSfBpNFhuvmKXGFE3HljQgH2pTk24qJex40vEA6t9WNkKj+b2haRhmJjnehGPZyjLiAvoXalji3B5HRagx4tdf/6okmKjC6kjIkjIHe3pMPwGbTeOO6OFmGt4ho7iksYAtCpkiAkhpzkLSfVNoBGov/xmXaA0IvVmHOzut7DbXlzcS14J4bZGEcd2ZHYpOk7cH582KlBVDBMrkGNU26rDMr2lxC+Dvz/mHre4AAmqoKrnAiQBom5+UAt925FnbvsfJY03RTYfINTCE1IkH5JnOYv+0VF8DqaQu2S8bvBBayydqeFVLeIXqVA7O5hFabGKJI+qa13TYRrzYUQzS9nF8UTEYaSfwJH5SE0y33jQZsWl9U2Vd/RYB8bsNtCBHuHGaa//xsY3Dwy9Fnr1CaLCePEUlo="


notifications:
  webhooks:
    urls:
      - https://webhooks.gitter.im/e/78a03685a7de695b89ac
    on_success: always  # options: [always|never|change] default: always
    on_failure: always  # options: [always|never|change] default: always
    on_start: never     # options: [always|never|change] default: always
